### ISSUE TITLE
New feature: Language Classification through character N-grams

### ISSUE THREAD

**Issue by BradKML** [coreygirard/classy#3]
https://github.com/daandouwe/char-lm uses character 1-grams, 2-grams, 3-grams, and 4-grams for language classification. It should be easy to update this repo to include this simple tweak. https://stackoverflow.com/a/50012407

**Comment by coreygirard** [comment]
Thanks for the suggestion, but it is beyond the scope of this project.

It is not intended to meet all possible usecases out-of-the-box, but instead to be simple, easy to understand, and easy to build upon for applications like the one mentioned above.
